// Copyright 2018-present Network Optix, Inc. Licensed under MPL 2.0: www.mozilla.org/MPL/2.0/

#pragma once

#include <map>
#include <memory>
#include <vector>
#include <string>

#include <nx/sdk/analytics/rect.h>
#include <nx/sdk/uuid.h>

namespace mimos {
namespace face_plugin {

// // Class labels for the MobileNet SSD model (VOC dataset).
// extern const std::vector<std::string> kClasses;
// extern const std::vector<std::string> kClassesToDetect;
// extern const std::map<std::string, std::string> kClassesToDetectPluralCapitalized;

/**
 * classlabel for face detection
 */
extern const std::string kFaceClassLabel;
extern const std::string kFaceClassLabelCapitalized; 

// /**
//  * Stores information about detection (one box per frame).
//  */
struct Detection
{
    nx::sdk::analytics::Rect boundingBox;
    float confidence;
    Landmarks landmarks;
    FaceEmbedding embedding;
    nx::sdk::Uuid trackId;

    std::string classLabel = kFaceClassLabel;        // "face"
    std::string recognizedName = "unknown";
    float similarityScore = 0.0f;
    std::string watchlist = "unknown";               // "whitelist", "blacklist", or "unknown"
};

/**
 * stores five key facial landmarks (two eyes, noses, two mouth corners)
 */
struct Landmark
{
    float x;
    float y;
};

using Landmarks = std::vector<Landmark>; // should contains 5 landmarks

/**
 * stores the high-dimensional vector/embedding for face recognition,
 * generated by arcface
 */
using FaceEmbedding = std::vector<float>; // e.g. a 512-dimensional vector

/**
 * Store information about detected face
 */
struct Detection
{
    // detected face bounding box
    const nx::sdk::analytics::Rect boundingBox;
    // confidence score of the face detection
    const float confidence;
    // 5 key face landmarks
    const Landmarks landmarks;
    // high dimensional face descriptor for recognition (arcface output)
    const FaceEmbedding embedding;
    // a unique id assigned to this face track over multiple frame
    const nx::sdk::Uuid trackId;
    // the classlabel is almost always face
    const std::string classLabel = "face";
    // the name of the recognized person from the database, or "unknown"
    const std::string recognizedName = "unknown";
    // the similarity score from recognition (consine similarity)
    const float similarityScore = 0.0f;
};

using DetectionList = std::vector<std::shared_ptr<Detection>>;

} // namespace face_plugin
} // namespace mimos
